# This is a basic workflow that is manually triggered

name: Deploy Application

on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - main  #  ветка

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: "rhammatov"
        password: "89991778287"

    - name: Build and push Docker image
      run: |
        docker build -t rhammatov/atom-front:latest Modules\Front\
        docker push rhammatov/atom-front:latest
    - name: Deploy to remote server
      uses: appleboy/ssh-action@master
      with:
        host: 95.174.94.138
        username: user1
        key: ${{ secrets.SSHKEY }}
        port: 22
        script: |
          docker stop atom-front || true
          docker rm atom-front || true
          docker rmi rhammatov/atomfront || true
          docker pull rhammatov/atom-front:latest || true
          docker run -d -ti --name atom-front -p 80:80 rhammatov/atom-front:latest
